Реализует вывод шагов игры
maver1cus/game-derby pull request #12
Opened 2021-02-16 16:05 UTC by maver1cus

2021-02-19 11:31 UTC, kicumkicum requested changes
Блин. Я сделал ревью пару дней назад и забыл его засабмитить, извини.

В целом все очень хорошо. Единственный архитектурно важный момент это symbol, который неявно связывает сущности с конкретным рендерингом. Напомни, пожалуйста, мне во вторник рассказать, как определять такие связи и научиться их не делать и я расскажу

2021-02-19 11:31 UTC, kicumkicum commented on src/engine/screen.js
> +      output[y][x] = element.symbol;
Получается, что `Car` и `Item` знают что-то о рендеринге, да еще и таком экзотическом. Это не хорошо. О таких нюансах знать должен именно тот, кто за этот рендеринг и отвечает

2021-02-19 11:31 UTC, kicumkicum commented on src/engine/screen.js
> +    }
По поводу разделения кода на блоки для удобного чтения.. Есть правила-неправила, что стоит добавдять пустую строку после блока объявлений переменных, перед `return`  и после закрывающей фигурной скобки

2021-02-19 11:31 UTC, kicumkicum commented on src/engine/screen.js
> +  static getSymbolForPrint(element) {
Пустой метод долой

2021-02-19 11:31 UTC, kicumkicum commented on src/engine/car.js
> +    return Directions[randomKey];
Пустую строку бы перед `return`

2021-02-25 13:49 UTC, maver1cus commented on src/engine/car.js
> +    return Directions[randomKey];
done

2021-02-25 13:49 UTC, maver1cus commented on src/engine/screen.js
> +  static getSymbolForPrint(element) {
done

2021-02-25 13:49 UTC, maver1cus commented on src/engine/screen.js
> +    }
done

2021-02-25 13:49 UTC, maver1cus commented on src/engine/screen.js
> +      output[y][x] = element.symbol;
done

2021-02-25 19:29 UTC, kicumkicum requested changes
Еще одно небольшое улучшение и можно мержить

2021-02-25 19:29 UTC, kicumkicum commented on src/engine/screen.js
> +    this._symbolsForItems = Screen.createSymbolsItemsForPrint([
Не обязательно хранить это в классе. Все что можно вынести за пределы класса, лучше вынести. Так ты облегчаешь тело класса и связанность кода, и повышаешь его структурность

2021-02-25 19:29 UTC, kicumkicum commented on src/engine/screen.js
> +    this._symbolsForItems = Screen.createSymbolsItemsForPrint([
Просто объяви переменную между объявлением класса и импортом

2021-02-25 19:29 UTC, kicumkicum commented on src/engine/screen.js
> +  static createSymbolsItemsForPrint(items) {
Эта функция напрямую с классом не связана. Ее можно объявить просто функцией

2021-02-26 11:41 UTC, maver1cus commented on src/engine/screen.js
> +  static createSymbolsItemsForPrint(items) {
done

2021-02-26 11:41 UTC, maver1cus commented on src/engine/screen.js
> +    this._symbolsForItems = Screen.createSymbolsItemsForPrint([
done

2021-03-01 11:49 UTC, kicumkicum approved these changes

2021-03-01 11:49 UTC, merged