Добавляет смену движения автомобиля при столкновении и конца карты, и вычисляет урон от столкновения
maver1cus/game-derby pull request #13
Opened 2021-03-04 12:32 UTC by maver1cus

2021-03-04 15:46 UTC, kicumkicum requested changes
Серёжа, все офигенно! Молодец 👍🏽

2021-03-04 15:46 UTC, kicumkicum commented on src/const.js
> +export const countDamageToCrash = 10;
Константы стоит именовать `ВОТ_ТАКИМ_СТИЛЕМ` - `COUNT_DAMAGE_TO_CRASH`

2021-03-04 15:46 UTC, kicumkicum commented on src/const.js
> +export const countDamageToCrash = 10;
И тут лучше подходит слово `value`, вместо `count`

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/car.js
> +  }
Добавь в эту функцию переносов строк, что бы было проще читать

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/car.js
> +    this._emitter = emitter;
`emitter` слишком общее название. Не очень понятно, что за ним скрывается, кроме того, что он шлет ивенты.

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/car.js
> +  _crash(element) {
Так как это обработчик события, то его стоит именовать с помощью суффиксов `on` или `handle`

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/emitter.js
> +  emit(event, ...args) {
О, ты сам его написал. Офигенно!

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/emitter.js
> +  emit(event, ...args) {
Но добавь переносов внутри методов

2021-03-04 15:46 UTC, kicumkicum commented on src/engine/world.js
> +          this._emitter.emit('world:end', element);
Названия событий стоит помещать в константы класса, который их испускает. Так проще работать с ними и отслеживать зависимости одних сущностей от других.

2021-03-11 17:03 UTC, maver1cus commented on src/const.js
> +export const countDamageToCrash = 10;
done

2021-03-11 17:03 UTC, maver1cus commented on src/engine/car.js
> +  }
done

2021-03-11 17:04 UTC, maver1cus commented on src/engine/car.js
> +    this._emitter = emitter;
done

2021-03-11 17:04 UTC, maver1cus commented on src/engine/car.js
> +  _crash(element) {
done

2021-03-11 17:04 UTC, maver1cus commented on src/engine/emitter.js
> +  emit(event, ...args) {
done

2021-03-11 17:04 UTC, maver1cus commented on src/engine/world.js
> +          this._emitter.emit('world:end', element);
done

2021-03-11 18:53 UTC, kicumkicum requested changes
Раньше циклическая зависимость была не явна. Сейчас она стала явная. Давай попробуем вообще от нее уйти

2021-03-11 18:53 UTC, kicumkicum commented on index.js
> +const emitter = new BusEvents();
А вот тут наоборот. Класс - это чистый event-emitter без конкретики. Но инстанс - это уже шина событий - появляется конкретика. Поэтому класс не нужно было переименовывать, а инстанс и свойство в `Car` нужно

2021-03-11 18:53 UTC, kicumkicum commented on src/engine/world.js
> +import Car from './car.js';
Смотри, у тебя появилась циклическая зависимость. Car зависит от World, а World от Car. Шина событий должна была развязать это, но пока не вышло

2021-03-17 12:05 UTC, maver1cus commented on src/engine/world.js
> +import Car from './car.js';
done

2021-03-17 12:05 UTC, maver1cus commented on index.js
> +const emitter = new BusEvents();
done

2021-03-21 07:59 UTC, kicumkicum commented on src/engine/item.js
> +    markElement._life = markElement._life - element._valueDamageToCrash;
Тут ты обращаешься к приватным свойствам. А так делать нельзя

2021-03-26 08:06 UTC, maver1cus commented on src/engine/item.js
> +    markElement._life = markElement._life - element._valueDamageToCrash;
done

2021-03-29 16:51 UTC, merged

2021-03-29 16:51 UTC, kicumkicum approved these changes