Render in browser
maver1cus/game-derby pull request #18
Opened 2021-04-04 17:45 UTC by maver1cus

2021-04-05 11:57 UTC, kicumkicum requested changes
Запустил. Выглядит офигенно! Нужна пара архитектурных улучшений и будет огонь!

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +  constructor(world, rootElement) {
Отлично, что рутовый элемент приходит снаружи. Это позволит встраивать скрин в любое место страницы 👍🏽

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +    this._display.width = this._displaySize.width;
Свойство класса используется, но оно не инициализируется в конструкторе. Это приводит к тому, что при знакомстве с новым классом/модулем (или вспоминая старый код), нужно прочитать много кода, чтобы его встретить. А затем в голове достроить "скелет" класса.

Чтобы упростить восприятие, принято все свойства, которые используются в классе, инициализировать в конструкторе. Если дефолтного значения нет, то записать в него `null`.

При таком подходе знакомство упрощается - сначала читаешь интерфейс - набор публичных методов. Потом свойства из конструктора - это позволяет тебе понять набор состояний, которые есть у класса. А потом, если потребуется, читаешь приватные методы.

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +  static create(world, rootElement) {
У тебя в каждом классе появляется статический метод `create`. Но в нем действительно есть необходимость?

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +  static create(world, rootElement) {
Давай не править код сразу, а просто обсудим

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +
Два переноса вместо одного. Пора подключать к проекту линтер, чтобы он занимался этим, а не мы)

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +    this._colorsELements = createColorsElementsForPrint(
Зачем это свойство нужно у инстанса, если оно никак не меняется ни от входных параметров, ни от внутреннего состояния?

2021-04-05 11:57 UTC, kicumkicum commented on src/engine/game.js
> +    this._canvasScreen = CanvasScreen.create(this._world, config.rootElement);
Теперь в проекте появился неиспользуемый модуль. По хорошему его нужно удалить, раз он не используется. Но в нем хорошая функциональность и вообще хотелось бы иметь возможность запускать игру в консоли тоже. Это быстрее, чем в браузере. Можно подключать тесты. Да и вообще)

Давай попробуем использовать тот или иной скрин в зависимости от окружения.

2021-04-19 08:35 UTC, maver1cus commented on src/engine/canvas-screen.js
> +    this._display.width = this._displaySize.width;
done

2021-04-19 08:36 UTC, maver1cus commented on src/engine/canvas-screen.js
> +  static create(world, rootElement) {
Я думаю он ненужен и его лучше удалить

2021-04-19 08:37 UTC, maver1cus commented on src/engine/canvas-screen.js
> +
Он подключен (google), но возможно надо донастроить

2021-04-19 08:37 UTC, maver1cus commented on src/engine/canvas-screen.js
> +    this._colorsELements = createColorsElementsForPrint(
done

2021-04-19 08:37 UTC, maver1cus commented on src/engine/game.js
> +    this._canvasScreen = CanvasScreen.create(this._world, config.rootElement);
done

2021-04-27 20:06 UTC, kicumkicum approved these changes
Все очень круто!

2021-04-27 20:06 UTC, kicumkicum commented on src/engine/canvas-screen.js
> +  static create(world, rootElement) {
Заведи ишью и в процессе можно будет сделать

2021-04-27 20:06 UTC, merged