Change javascript to typescript
maver1cus/game-derby pull request #20
Opened 2021-05-07 08:21 UTC by maver1cus

2021-05-07 09:24 UTC, kicumkicum requested changes
Ктуряг! Посмотрел часть, выглядит офигенно. На выходных посмотрю остальное

2021-05-07 09:24 UTC, kicumkicum commented on package.json
> +  "name": "excel-ts",
Что-то пошло не так))

2021-05-07 09:24 UTC, kicumkicum commented on package.json
> +  "main": "webpack.config.js",
И тут

2021-05-07 09:24 UTC, kicumkicum commented on package.json
> +    "eslint": "eslint src/**/*.ts",
Лучше использовать опцию `--ext`, для указания расширения файлов. Тогда линтинг не будет падать, если в директории вдруг не окажется файлов. Ну и будет проще, когда нужно линтить разные расширения, вроде `ts, tsx`

2021-05-07 09:24 UTC, kicumkicum commented on src/engine/car/car.interface.ts
> +  handleWorldEnd(element: Item): void;
Тут так же стоит использовать интерфейс `IItem`. Если можно обойтись от реализации в типах, в замен на интерфейс, то лучше так и сделать

2021-05-07 09:24 UTC, kicumkicum commented on src/engine/car/car.ts
> +import ICar from './car.interface';
FYI Можно именовать файлы интерфейсов в виде `i-car`. Достаточно часто встречается такое

2021-05-07 09:24 UTC, kicumkicum commented on src/engine/car/car.ts
> +  getDirectionRide():string {
Тут и ниже просится пробельчик перед типом

2021-05-11 16:32 UTC, kicumkicum requested changes
Все оч круто!

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/car/car.ts
> +import ICar from './car.interface';
Но в целом суффиксы хороши. Когда проект большой, то по ним удобнее парсить исходники

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/car/car.ts
> +  static getRandomDirection(): string {
Если бы Direction был енумом, то типизация была более наглядной

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/emitter/emitter.ts
> +  subscribe(event:string, fn:Function) {
Функции лучше типизировать через `() => type`. Это более наглядно и нужно явно указать типы

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/console-screen/console-screen.ts
> +  print() {
Не указаны возвращаемые значения

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/console-screen/console-screen.ts
> +        .map((row:[]) => row.map(() => ' '));
Внутри методов массива как правило, можно не указывать типы, потому что они вычисляются самим ТСом

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/game/game.ts
> +      : new ConsoleScreen(this.world);
Давай обсудим, как можно отвязать `Game` от конкретных реализаций `Screen`? Код писать не нужно, просто обсудим

2021-05-11 16:32 UTC, kicumkicum commented on src/engine/world/world.ts
> +  busEvents: BusEvents;
Если они публичные, то стоит это указать. Так намерения будут более четкими и я буду понимать, что ты именно так и хотел, а не забыл написать `private`

2021-05-11 16:32 UTC, kicumkicum commented on src/utils.ts
> +export const getRandomInteger = function(a = 0, b = 1): number {
Давай заюзаем тут стрелочные. А то чего они не как все)

2021-05-12 17:30 UTC, kicumkicum commented on src/engine/game/game.ts
> +      : new ConsoleScreen(this.world);
Обсудили. Пришли к выводу, что `Game` должен зависить только от интерфейса `IScreen`

2021-05-20 12:12 UTC, maver1cus commented on package.json
> +  "name": "excel-ts",
done

2021-05-20 12:12 UTC, maver1cus commented on package.json
> +  "main": "webpack.config.js",
done

2021-05-20 12:12 UTC, maver1cus commented on package.json
> +    "eslint": "eslint src/**/*.ts",
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/car/car.interface.ts
> +  handleWorldEnd(element: Item): void;
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/car/car.ts
> +import ICar from './car.interface';
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/car/car.ts
> +  getDirectionRide():string {
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/car/car.ts
> +  static getRandomDirection(): string {
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/emitter/emitter.ts
> +  subscribe(event:string, fn:Function) {
done

2021-05-20 12:12 UTC, maver1cus commented on src/engine/console-screen/console-screen.ts
> +  print() {
done

2021-05-20 12:13 UTC, maver1cus commented on src/engine/console-screen/console-screen.ts
> +        .map((row:[]) => row.map(() => ' '));
done

2021-05-20 12:13 UTC, maver1cus commented on src/engine/game/game.ts
> +      : new ConsoleScreen(this.world);
done

2021-05-20 12:13 UTC, maver1cus commented on src/engine/world/world.ts
> +  busEvents: BusEvents;
done

2021-05-20 12:13 UTC, maver1cus commented on src/utils.ts
> +export const getRandomInteger = function(a = 0, b = 1): number {
done

2021-05-22 07:54 UTC, kicumkicum requested changes
Давай с IScreen разберемся в Game и сольем

2021-05-22 07:54 UTC, kicumkicum commented on src/engine/car/car.ts
> +      speed:number,
Тут бы пробельчик после двоеточия. Наверно надо будет прикрутить правило для линтера, чтобы не думать о проблемах стиля. Заведи ишью на это, пожалуйста

2021-05-22 07:54 UTC, kicumkicum commented on src/engine/game/game.ts
> +      : new ConsoleScreen(this.world);
Ну, пока он всё так же не зависит от IScreen

2021-05-23 19:27 UTC, maver1cus commented on src/engine/game/game.ts
> +      : new ConsoleScreen(this.world);
done

2021-05-23 19:28 UTC, maver1cus commented on src/engine/car/car.ts
> +      speed:number,
done

2021-05-24 10:59 UTC, kicumkicum approved these changes
Огонь огонь огонь

2021-05-24 11:00 UTC, merged