fix cycle dependence
maver1cus/game-derby pull request #21
Opened 2021-05-25 11:08 UTC by maver1cus

2021-06-01 15:59 UTC, kicumkicum requested changes
Есть странные места, но думаю они не от хорошей жизни)) Сегодня мы их обсудим

2021-06-01 15:59 UTC, kicumkicum commented on src/engine/canvas-screen/canvas-screen.ts
> +import Car from '../car/car';
А почему поменялся порядок импортов? Это влияло на что-нибудь?

2021-06-01 15:59 UTC, kicumkicum commented on src/engine/game/game.ts
> +import {createScreen} from '../../utils/createScreen';
FYI Функции или модули, которые создают сущности, называются фабриками - factory.
Например, статические методы `create`, которые ты использовал, называются фабричными методами. Можно переименовать модуль в `screen-factory` и из него импортировать функцию `createScreen`.

2021-06-01 15:59 UTC, kicumkicum commented on src/engine/item/item.inteface.ts
> +  getSpeed?(): number;
А у какого айтема есть этот метод?

2021-06-01 15:59 UTC, kicumkicum commented on src/engine/world/world.ts
> -        if (element.getSpeed) {
У `Car` может не быть этого метода?

2021-06-01 15:59 UTC, kicumkicum commented on src/engine/world/world.ts
> +        .filter((element) => 'getSpeed' in element)
Ну такая себе проверка. Она у тебя и тут, и там. Надо сделать так, чтобы эта проверка не нужна была. А то когда видишь подобные проверки на метод, уверенности в коде это не добавляет

2021-06-01 17:17 UTC, maver1cus commented on .eslintrc
> +    "import/no-cycle": 2
test comment

2021-06-02 19:20 UTC, maver1cus commented on src/engine/canvas-screen/canvas-screen.ts
> +import Car from '../car/car';
done

2021-06-02 19:20 UTC, maver1cus commented on src/engine/game/game.ts
> +import {createScreen} from '../../utils/createScreen';
done

2021-06-02 19:21 UTC, maver1cus commented on src/engine/item/item.inteface.ts
> +  getSpeed?(): number;
done

2021-06-02 19:21 UTC, maver1cus commented on src/engine/world/world.ts
> -        if (element.getSpeed) {
done

2021-06-02 19:21 UTC, maver1cus commented on src/engine/world/world.ts
> +        .filter((element) => 'getSpeed' in element)
done

2021-06-02 19:21 UTC, maver1cus commented on .eslintrc
> +    "import/no-cycle": 2
done

2021-06-07 17:12 UTC, kicumkicum approved these changes

2021-06-07 17:12 UTC, merged