Add test
maver1cus/game-derby pull request #27
Opened 2021-07-08 14:14 UTC by maver1cus

2021-07-08 17:33 UTC, kicumkicum requested changes
Все просто отлично! Нужно только
- [x] Добавить скрипт запуска тестов

2021-07-08 17:33 UTC, kicumkicum commented on package.json
> +    "jest": "^27.0.6"
Jest нужен  в Dev зависимостях. Он же не работает в клиентском коде

2021-07-08 17:33 UTC, kicumkicum commented on tsconfig.json
> +    "esModuleInterop": true
А что делает это свойство?

2021-07-09 06:56 UTC, maver1cus commented on package.json
> +    "jest": "^27.0.6"
done

2021-07-09 06:58 UTC, maver1cus commented on tsconfig.json
> +    "esModuleInterop": true
что бы jest import в ES mudule понимал

2021-07-09 16:51 UTC, kicumkicum approved these changes

2021-07-09 16:51 UTC, merged