добавляет ТЗ
maver1cus/game-derby pull request #5
Opened 2021-02-02 17:11 UTC by maver1cus

создает файл SPECIFICATION.md с техническим заданием

2021-02-02 17:50 UTC, kicumkicum requested changes

2021-02-02 17:50 UTC, kicumkicum commented on SPECIFICATION.md
> +# **Derby**
Дополнительно стилизовать заголовок нет необходимости. H1 с этим сам прекрасно справляется

2021-02-03 06:28 UTC, maver1cus commented on SPECIFICATION.md
> +# **Derby**
done

2021-02-03 07:22 UTC, kicumkicum approved these changes

2021-02-03 07:22 UTC, merged