Добавляет начальную архитектуру проекта
maver1cus/game-derby pull request #6
Opened 2021-02-03 17:05 UTC by maver1cus

2021-02-03 19:36 UTC, kicumkicum requested changes
Отличное начало!

2021-02-03 19:36 UTC, kicumkicum commented on src/components/game.js
> +  static create(config) {
Лучше помещать статические методы в конец класса. То есть порядок методов такой:

```js
class Foo() {
  publicMethod() {}

  _privateMethod() {}

  static staticMethod() {}
}
```

Типа, в начале ты видишь публичный интерфейс класса. Чтобы посмотреть статику, тебе нужно перейти в конец файла. А середина класса с приватными методами не сильно интересная, потому что это уже особенности реализации.

2021-02-03 19:36 UTC, kicumkicum commented on src/components/game.js
> +    this.config = config;
У большинства классов свойства должны быть приватными, чтобы к ним нельзя было получить доступ снаружи. В JS приватных данных особо не завезли, поэтому разработчики договорились помечать приватные данные нижним подчеркиванием. `this._config = config`

2021-02-03 19:36 UTC, kicumkicum commented on index.js
> +import Game from './src/components/game.js';
Только это не компоненты. Под компонентами обычно понимают UI-компоненты. А это просто части игры. Можно назвать директорию `game` или `engine` или еще что-то подобное.

2021-02-04 06:41 UTC, maver1cus commented on src/components/game.js
> +  static create(config) {
done

2021-02-04 06:42 UTC, maver1cus commented on src/components/game.js
> +    this.config = config;
done

2021-02-04 06:42 UTC, maver1cus commented on index.js
> +import Game from './src/components/game.js';
done

2021-02-04 13:35 UTC, kicumkicum approved these changes
Все круто!

2021-02-04 13:35 UTC, merged