Реализует перемещение автомобилей
maver1cus/game-derby pull request #7
Opened 2021-02-06 09:03 UTC by maver1cus

- добавляет класс Universe
- разделяет config игры на отдельные сущности
- создает utils и const
- добавляет метод передвижение Car

2021-02-08 11:56 UTC, kicumkicum requested changes
Код хорошо написан, но есть слабые стороны у основной задачи. Один коммент призывает к обсуждению этой реализации

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/universe.js
> +export default class Universe {
Я не очень большой знаток английского и возможно по этому это слово я перевожу как универсальный. Потом я понимаю, что что-то не то и лезу в переводчик. Я такой не один. Когда кто-то будет читать твой код, он не сможет залезть тебе в голову, но нужно, чтобы он понял. Тем более, этим кем-то можешь быть и ты через пол года. 

При выборе имени стоит руководствоваться правилом Проще - лучше. Брать то, что лежит на поверхности. Например, альтернатива ускоренной это слово Мир world. Или space(но это уже не очень, потому что или пространство, или космос). Или система координат

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/universe.js
> +  validateCoords(coords) {
В методе происходит изменение внешних (входных данных). Это не очень хорошая практика, потому что нельзя менять чужое.

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/universe.js
> +export default class Universe {
Сейчас класс содержит размерность карты и набор методов-валидаторов. Больше он ничего не делает. Возникает вопрос, нужен ли он на самом деле или можно обойтись парой утилитарных функций и константой с размерностью карты?

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/universe.js
> +  isValidCoordX(coordsX) {
Если метод не используется снаружи, то его лучше сделать приватным

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/game.js
> +    this._cars.forEach(car => car.moving(direction, this._universe));
Сейчас расклад такой, что за движение отвечает три сущности `Game`, `Car`, `Universe`. Логика размазалась по нескольким местам и с ней будет сложно работать (в силу человеческой ограниченности).

Попробуй сделать предположение текстом, без кода, как можно упростить реализацию перемещения объектов в игре. Где какую логику разместить.

2021-02-08 11:56 UTC, kicumkicum commented on src/engine/universe.js
> +      coords.x = (coords.x < 0)
Зарядка для ума - как можно написать это, используя `Math.min/Math.max`?

2021-02-10 07:30 UTC, maver1cus commented on src/engine/universe.js
> +      coords.x = (coords.x < 0)
done

2021-02-10 07:30 UTC, maver1cus commented on src/engine/universe.js
> +  isValidCoordX(coordsX) {
done

2021-02-10 07:30 UTC, maver1cus commented on src/engine/universe.js
> +export default class Universe {
done

2021-02-10 07:30 UTC, maver1cus commented on src/engine/universe.js
> +export default class Universe {
done

2021-02-10 07:30 UTC, maver1cus commented on src/engine/universe.js
> +  validateCoords(coords) {
done

2021-02-11 16:47 UTC, kicumkicum requested changes
Все круто! Начинают всплывать взрослые вещи из мира ООП. Я их описал ниже. Сейчас их фиксить не нужно - лучше сделать позже, потому что явно они фичу не блокируют. Заведи, пожалуйста, по такске на каждую. Про инверсию зависимостей можно почитать статейки, чтобы понять о чем вообще речь

Необходимый рефакторинг в будущем:
- [ ] Константные строки поместить в енумы. Строки отстой сами по себе, хотя бы потому что сложно искать вхождения
- [ ] Инстанцирование объектов убрать за пределы класса (инверсия зависимостей)

2021-02-11 16:47 UTC, kicumkicum commented on src/engine/world.js
> +  render() {
Метод ничего не рендерит. Он просто обновляет положение предметов

2021-02-11 16:47 UTC, kicumkicum commented on src/engine/world.js
> +    this.i = 0;
Вроде как не используется

2021-02-11 16:47 UTC, kicumkicum commented on src/utils.js
> +export const getDirection = () => getRandomItemFromArray(DIRECTIONS);
Я бы порекомендовал объявлять функции полным синтаксисом. Так их проще считывать, когда быстро читаешь код. Чем меньше вариативности в визуальных паттернах, тем проще мозгу работать. Но это не жесткое правило, просто мое наблюдение. Это относится к вкусовщине.

2021-02-11 16:47 UTC, kicumkicum commented on src/utils.js
> +export const getDirection = () => getRandomItemFromArray(DIRECTIONS);
`getDirection` уже контекстная функция. Ее лучше объявить ближе к месту использования

2021-02-11 16:47 UTC, kicumkicum commented on src/engine/world.js
> +        switch (direction) {
Рекомендую отбивать пустой строкой объявление переменных и код

2021-02-11 16:47 UTC, kicumkicum commented on src/engine/world.js
> +
Лишняя пустая строка и нет `;` ниже

2021-02-11 16:47 UTC, kicumkicum commented on src/engine/item.js
> +  }
Пустой конструктор можно не писать. И даже нужно не писать

2021-02-12 13:30 UTC, maver1cus commented on src/engine/world.js
> +  render() {
done

2021-02-12 13:30 UTC, maver1cus commented on src/engine/world.js
> +    this.i = 0;
done

2021-02-12 13:30 UTC, maver1cus commented on src/utils.js
> +export const getDirection = () => getRandomItemFromArray(DIRECTIONS);
done

2021-02-12 13:30 UTC, maver1cus commented on src/utils.js
> +export const getDirection = () => getRandomItemFromArray(DIRECTIONS);
done

2021-02-12 13:31 UTC, maver1cus commented on src/engine/world.js
> +        switch (direction) {
done

2021-02-12 13:31 UTC, maver1cus commented on src/engine/world.js
> +
done

2021-02-12 13:31 UTC, maver1cus commented on src/engine/item.js
> +  }
done

2021-02-13 10:51 UTC, kicumkicum commented on src/utils.js
> +export const getRandomInteger = function(a = 0, b = 1) {
Возможно я не корректно выразил свою мысль. В целом стрелочные функции лучше обычных function. Но однострочные стрелочные функции лучше использовать, когда ты их передаешь в качестве колбека. А когда ты создаешь функцию и сохраняешь в переменную, то лучше использовать полный ее синтаксис

```js
const foo = () => {
  return 42;
};
```

2021-02-13 10:52 UTC, kicumkicum approved these changes

2021-02-13 10:52 UTC, merged